### PR TITLE
To-Do List

### PR DESCRIPTION
**Pull request by verissimohenry**
Simple To-Do-List, using Node and Webpack functionality, In this project, you have the ability to add projects, add tasks that you have to do to a project, including its description, date to be done, and priority.

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly
- [ ] App works perfectly fine.
## To Improve 🙏
- [x] PR summary should explain the features implemented. Please add a descriptive PR summary.
- [x] App should use Webpack to bundle the project files. Please use Webpack properly as learnt in previous lesson.
- [x] Please add `webpack-dev-server` in `package.json` as dev dependencies. 
- [x] Commands like build, and development should be in package.json inside `scripts'.
- [x] Please do not disable eslint rules and correct the errors detected by them.
- [x] Please use ES6 arrow functions intead of function keyword.

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Review by taiwo2 — CHANGES_REQUESTED** [review]
Hey @verissimohenry Great job is done and i must commend your effort in trying to implement suggested changes by the previous Code reviewer, however, few changes are required 
### Highlights
The app should use Webpack to bundle the project files. Please use Webpack properly as learned in the previous lesson.
Webpack-dev-server in package.json as dev dependencies.
Commands like build, and development should be in package.json inside `scripts'.
PR summary should explain the features implemented

#### To improve

- [x] Please use ES6 arrow functions instead of function keywords.
- [x] Kindly state how to run your app in your readme file
- [x] I ran into an error when I run npm` run build`
`Module not found: Error: Can't resolve 'sass-loader' in '/home/taiwo/microverse/to-do-list`

### [OPTIONAL]
- [x] There should be  a 'default' project
- [x] DOM-Manipulation and Logic are in separate modules ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))

# once specific changes are made kindly request another review

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️🛑️🛑️**

Hello team,
Great work making the requested changes.
However, let's make a small change and get it approved

[REQUESTED]: Kindly add node_modules to gitignore.

That's it👍️👍️

Make the requested changes and get it approved 👍️👍️

Happy coding💻️💻️

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED👍️👍️👍️**

Hello team,
Great work making the required changes

You can merge👍️👍️

Happy coding💻️💻️

**Pull request merged**
